version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: esteemgift
    container_name: EsteemGiftContainer
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - nginx
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: NginxContainer
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - laravel

networks:
  laravel:
    driver: bridge