version: "3.9"
services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    privileged: true
    user: root
    restart: on-failure
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
  agent:
    image: jenkins/ssh-agent:jdk11
    container_name: jenkins_agent
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
volumes:
  jenkins_home: